### ISSUE TITLE
Doctor Who - Playfield.dev - Coin Door Open switch not working

### ISSUE THREAD

**Issue by xantari** [neophob/wpc-emu#138]
You should get a DMD warning after flipping the coin door switch, but it isn't doing anything at https://playfield.dev/ for Dr Who.

**Comment by neophob** [comment]
Thanks Xantari, after I opened the coin door it taskes some seconds then you see this image:

<img width="726" alt="Bildschirm­foto 2023-03-28 um 14 32 17" src="https://user-images.githubusercontent.com/837347/228237015-997a5ed0-2e72-4100-b620-9766d591f54c.png">

do you have a video that shows the issue on a real pinball?

**Comment by neophob** [comment]
I don't know, that's why I wanted to see this on a real machine
