### ISSUE TITLE
BitMagic documentation / implementation mismatch

### ISSUE THREAD

**Issue by ecurtz** [neophob/wpc-emu#73]
As described here on the C# port the BitMagic function for MSB doesn't actually perform as the comment implies and the current implementation will break if more than a single bit is set.

https://github.com/jsm174/wpc-emu-cs/issues/1#issue-746781527

**Comment by neophob** [comment]
Thanks @ecurtz - the comment was pretty banana! I just removed the useless comment anyway and added a test case!

**Comment by neophob** [comment]
https://github.com/neophob/wpc-emu/commit/c150b3d7c38b81027105d3bcfb39e44cd643353d is the fix
